I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 76, in script
    show yx left
Exception: Image 'yx' does not accept attributes 'left'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 76, in script
    show yx left
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\ast.py", line 1388, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\ast.py", line 1351, in show_imspec
    renpy.config.show(name,
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\display\image.py", line 413, in find_target
    self.target = target._duplicate(a)
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'yx' does not accept attributes 'left'.

Windows-10-10.0.18362 AMD64
Ren'Py 8.0.0.22062402
VlastVN 1.0
Sun Jul  3 20:13:59 2022
