I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 378, in script
    o "ACTION CALCULATED, SUCCES PROBABILITY 89 % "
ValueError: incomplete format

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 378, in script
    o "ACTION CALCULATED, SUCCES PROBABILITY 89 % "
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\ast.py", line 901, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\PROGRAMAS\renpy\renpy-8.0.0-sdk\renpy\exports.py", line 1362, in say
    what = what % tag_quoting_dict
ValueError: incomplete format

Windows-10-10.0.18362 AMD64
Ren'Py 8.0.0.22062402
VlastVN 1.0
Tue Jul  5 01:15:55 2022
